shellEmulator: true

packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  esbuild: true
  unrs-resolver: true
  vue-demi: true
  workerd: true

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
  - vue-demi
  - workerd
