import {
  MAX_CLASS_CAPACITY,
  type BookingRecord,
  type Parent,
  type PaymentAttempt,
  type Student,
  type TrialClass,
} from '@trial-booking/shared';

export interface SeedSnapshot {
  parents: Parent[];
  students: Student[];
  trialClasses: TrialClass[];
  bookings: BookingRecord[];
  paymentAttempts: PaymentAttempt[];
}

export function createInitialSeedSnapshot(): SeedSnapshot {
  const parents: Parent[] = [
    {
      id: 'par-budi',
      name: 'Budi Santoso',
      email: 'budi.santoso@example.com',
      phone: '+62-812-3000-1001',
    },
    {
      id: 'par-siti',
      name: 'Siti Rahma',
      email: 'siti.rahma@example.com',
      phone: '+62-812-3000-1002',
    },
    {
      id: 'par-andi',
      name: 'Andi Wijaya',
      email: 'andi.wijaya@example.com',
      phone: '+62-812-3000-1003',
    },
    {
      id: 'par-hendra',
      name: 'Hendra Pratama',
      email: 'hendra.pratama@example.com',
      phone: '+62-812-3000-1004',
    },
    {
      id: 'par-dewi',
      name: 'Dewi Putri',
      email: 'dewi.putri@example.com',
      phone: '+62-812-3000-1005',
    },
  ];

  const students: Student[] = [
    {
      id: 'stu-dina',
      parentId: 'par-budi',
      name: 'Dina Santoso',
      age: 9,
      gradeLevel: 'Grade 4',
    },
    {
      id: 'stu-raka',
      parentId: 'par-budi',
      name: 'Raka Santoso',
      age: 11,
      gradeLevel: 'Grade 5',
    },
    {
      id: 'stu-arka',
      parentId: 'par-siti',
      name: 'Arka Rahma',
      age: 9,
      gradeLevel: 'Grade 4',
    },
    {
      id: 'stu-nadia',
      parentId: 'par-siti',
      name: 'Nadia Rahma',
      age: 10,
      gradeLevel: 'Grade 5',
    },
    {
      id: 'stu-evan',
      parentId: 'par-andi',
      name: 'Evan Wijaya',
      age: 9,
      gradeLevel: 'Grade 4',
    },
    {
      id: 'stu-rafi',
      parentId: 'par-hendra',
      name: 'Rafi Pratama',
      age: 9,
      gradeLevel: 'Grade 4',
    },
    {
      id: 'stu-kayla',
      parentId: 'par-dewi',
      name: 'Kayla Putri',
      age: 9,
      gradeLevel: 'Grade 4',
    },
  ];

  const trialClasses: TrialClass[] = [
    {
      id: 'cls-math-fractions',
      title: 'Visual Fractions & Ratios Lab',
      subject: 'Math',
      gradeRange: 'Grade 4',
      teacherName: 'Ms. Clara Tan',
      scheduledAt: '2026-09-26T10:00:00+07:00',
      durationMinutes: 60,
      priceIdr: 75000,
      maxCapacity: MAX_CLASS_CAPACITY,
    },
    {
      id: 'cls-sci-orbit',
      title: 'Planetary Orbits & Gravity Physics',
      subject: 'Science',
      gradeRange: 'Grade 5',
      teacherName: 'Mr. Daniel Lim',
      scheduledAt: '2026-09-27T14:00:00+07:00',
      durationMinutes: 60,
      priceIdr: 75000,
      maxCapacity: MAX_CLASS_CAPACITY,
    },
    {
      id: 'cls-math-logic',
      title: 'Algorithmic Puzzles & Game Logic',
      subject: 'Math',
      gradeRange: 'Grade 3–4',
      teacherName: 'Ms. Sarah Chen',
      scheduledAt: '2026-09-27T16:00:00+07:00',
      durationMinutes: 60,
      priceIdr: 75000,
      maxCapacity: MAX_CLASS_CAPACITY,
    },
  ];

  const bookings: BookingRecord[] = [
    // Class 1: Visual Fractions & Ratios Lab — 3/4 confirmed students (1 seat left: Seat 4)
    {
      id: 'bkg-seed-01',
      parentId: 'par-hendra',
      studentId: 'stu-rafi',
      trialClassId: 'cls-math-fractions',
      seatNumber: 1,
      status: 'confirmed',
      conflictReason: null,
      conflictingBookingId: null,
      version: 2,
      createdAt: '2026-09-24T08:00:00.000Z',
      updatedAt: '2026-09-24T08:01:00.000Z',
      confirmedAt: '2026-09-24T08:01:00.000Z',
    },
    {
      id: 'bkg-seed-02',
      parentId: 'par-dewi',
      studentId: 'stu-kayla',
      trialClassId: 'cls-math-fractions',
      seatNumber: 2,
      status: 'confirmed',
      conflictReason: null,
      conflictingBookingId: null,
      version: 2,
      createdAt: '2026-09-24T08:05:00.000Z',
      updatedAt: '2026-09-24T08:06:00.000Z',
      confirmedAt: '2026-09-24T08:06:00.000Z',
    },
    {
      id: 'bkg-seed-03',
      parentId: 'par-andi',
      studentId: 'stu-evan',
      trialClassId: 'cls-math-fractions',
      seatNumber: 3,
      status: 'confirmed',
      conflictReason: null,
      conflictingBookingId: null,
      version: 2,
      createdAt: '2026-09-24T08:10:00.000Z',
      updatedAt: '2026-09-24T08:11:00.000Z',
      confirmedAt: '2026-09-24T08:11:00.000Z',
    },
    // Pre-seeded Pending Checkout for User A (Arka Rahma) on Seat 4 of Visual Fractions Lab
    {
      id: 'bkg-seed-pending-arka',
      parentId: 'par-siti',
      studentId: 'stu-arka',
      trialClassId: 'cls-math-fractions',
      seatNumber: 4,
      status: 'pending_payment',
      conflictReason: null,
      conflictingBookingId: null,
      version: 1,
      createdAt: '2026-09-24T09:00:00.418Z',
      updatedAt: '2026-09-24T09:00:00.418Z',
      confirmedAt: null,
    },
    // Class 2: Planetary Orbits & Gravity Physics — 1/4 confirmed + 1 payment_failed
    {
      id: 'bkg-seed-04',
      parentId: 'par-budi',
      studentId: 'stu-dina',
      trialClassId: 'cls-sci-orbit',
      seatNumber: 1,
      status: 'confirmed',
      conflictReason: null,
      conflictingBookingId: null,
      version: 2,
      createdAt: '2026-09-24T08:20:00.000Z',
      updatedAt: '2026-09-24T08:21:00.000Z',
      confirmedAt: '2026-09-24T08:21:00.000Z',
    },
    {
      id: 'bkg-seed-failed-nadia',
      parentId: 'par-siti',
      studentId: 'stu-nadia',
      trialClassId: 'cls-sci-orbit',
      seatNumber: 2,
      status: 'payment_failed',
      conflictReason: 'PAYMENT_DECLINED',
      conflictingBookingId: null,
      version: 2,
      createdAt: '2026-09-24T08:30:00.000Z',
      updatedAt: '2026-09-24T08:31:00.000Z',
      confirmedAt: null,
    },
    // Class 3: Algorithmic Puzzles & Game Logic — 4/4 confirmed (Full Capacity)
    {
      id: 'bkg-seed-05',
      parentId: 'par-hendra',
      studentId: 'stu-rafi',
      trialClassId: 'cls-math-logic',
      seatNumber: 1,
      status: 'confirmed',
      conflictReason: null,
      conflictingBookingId: null,
      version: 2,
      createdAt: '2026-09-24T07:00:00.000Z',
      updatedAt: '2026-09-24T07:01:00.000Z',
      confirmedAt: '2026-09-24T07:01:00.000Z',
    },
    {
      id: 'bkg-seed-06',
      parentId: 'par-dewi',
      studentId: 'stu-kayla',
      trialClassId: 'cls-math-logic',
      seatNumber: 2,
      status: 'confirmed',
      conflictReason: null,
      conflictingBookingId: null,
      version: 2,
      createdAt: '2026-09-24T07:05:00.000Z',
      updatedAt: '2026-09-24T07:06:00.000Z',
      confirmedAt: '2026-09-24T07:06:00.000Z',
    },
    {
      id: 'bkg-seed-07',
      parentId: 'par-andi',
      studentId: 'stu-evan',
      trialClassId: 'cls-math-logic',
      seatNumber: 3,
      status: 'confirmed',
      conflictReason: null,
      conflictingBookingId: null,
      version: 2,
      createdAt: '2026-09-24T07:10:00.000Z',
      updatedAt: '2026-09-24T07:11:00.000Z',
      confirmedAt: '2026-09-24T07:11:00.000Z',
    },
    {
      id: 'bkg-seed-08',
      parentId: 'par-budi',
      studentId: 'stu-raka',
      trialClassId: 'cls-math-logic',
      seatNumber: 4,
      status: 'confirmed',
      conflictReason: null,
      conflictingBookingId: null,
      version: 2,
      createdAt: '2026-09-24T07:15:00.000Z',
      updatedAt: '2026-09-24T07:16:00.000Z',
      confirmedAt: '2026-09-24T07:16:00.000Z',
    },
  ];

  const paymentAttempts: PaymentAttempt[] = [
    {
      id: 'pay-seed-01',
      bookingId: 'bkg-seed-01',
      amountIdr: 75000,
      method: 'card_visa_4242',
      status: 'succeeded',
      errorCode: null,
      message: 'Payment captured and seat #1 confirmed.',
      createdAt: '2026-09-24T08:01:00.000Z',
    },
    {
      id: 'pay-seed-02',
      bookingId: 'bkg-seed-02',
      amountIdr: 75000,
      method: 'card_visa_4242',
      status: 'succeeded',
      errorCode: null,
      message: 'Payment captured and seat #2 confirmed.',
      createdAt: '2026-09-24T08:06:00.000Z',
    },
    {
      id: 'pay-seed-03',
      bookingId: 'bkg-seed-03',
      amountIdr: 75000,
      method: 'qris_instant',
      status: 'succeeded',
      errorCode: null,
      message: 'QRIS payment settled and seat #3 confirmed.',
      createdAt: '2026-09-24T08:11:00.000Z',
    },
    {
      id: 'pay-seed-04',
      bookingId: 'bkg-seed-04',
      amountIdr: 75000,
      method: 'card_visa_4242',
      status: 'succeeded',
      errorCode: null,
      message: 'Payment captured and seat #1 confirmed.',
      createdAt: '2026-09-24T08:21:00.000Z',
    },
    {
      id: 'pay-seed-failed-nadia',
      bookingId: 'bkg-seed-failed-nadia',
      amountIdr: 75000,
      method: 'card_declined_0002',
      status: 'failed',
      errorCode: 'CARD_DECLINED',
      message: 'Issuer declined card ending 0002. Student was not added to class roster.',
      createdAt: '2026-09-24T08:31:00.000Z',
    },
    {
      id: 'pay-seed-05',
      bookingId: 'bkg-seed-05',
      amountIdr: 75000,
      method: 'card_visa_4242',
      status: 'succeeded',
      errorCode: null,
      message: 'Payment captured and seat #1 confirmed.',
      createdAt: '2026-09-24T07:01:00.000Z',
    },
    {
      id: 'pay-seed-06',
      bookingId: 'bkg-seed-06',
      amountIdr: 75000,
      method: 'card_visa_4242',
      status: 'succeeded',
      errorCode: null,
      message: 'Payment captured and seat #2 confirmed.',
      createdAt: '2026-09-24T07:06:00.000Z',
    },
    {
      id: 'pay-seed-07',
      bookingId: 'bkg-seed-07',
      amountIdr: 75000,
      method: 'card_visa_4242',
      status: 'succeeded',
      errorCode: null,
      message: 'Payment captured and seat #3 confirmed.',
      createdAt: '2026-09-24T07:11:00.000Z',
    },
    {
      id: 'pay-seed-08',
      bookingId: 'bkg-seed-08',
      amountIdr: 75000,
      method: 'card_visa_4242',
      status: 'succeeded',
      errorCode: null,
      message: 'Payment captured and seat #4 confirmed.',
      createdAt: '2026-09-24T07:16:00.000Z',
    },
  ];

  return {
    parents,
    students,
    trialClasses,
    bookings,
    paymentAttempts,
  };
}
